### ISSUE TITLE
[Bug] YAML parsing error after bump to 1.7.0

### ISSUE THREAD

**Issue by younsl** [hahwul/deadfinder#77]
## Bug Description

deadfinder@1.7.0 fails to load due to YAML parsing error in action.yml, while the same configuration works in v1.6.1.

This actions error message suggests there's a YAML parsing issue in the action.yml file of version 1.7.0.

```bash
Error: hahwul/deadfinder/1.7.0/action.yml: (Line: 9, Col: 57, Idx: 229): Mapping values are not allowed in this context.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
```

## Reproduction

Working in deadfinder@v1.6.1:

```yaml
# .github/workflows/broken-link-finder.yml
jobs:
  deadfinder:
    runs-on: ubuntu-24.04
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.6.1
      id: broken-link
      with:
        command: sitemap
        target: https://your.homepage.com/sitemap.xml
    
    - name: Output Handling
      run: echo ${{ steps.broken-link.outputs.output }}
```

Failing in v1.7.0 with identical configuration:

```yaml
# .github/workflows/broken-link-finder.yml
jobs:
  deadfinder:
    runs-on: ubuntu-24.04
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.7.0
      id: broken-link
      with:
        command: sitemap
        target: https://your.homepage.com/sitemap.xml
    
    - name: Output Handling
      run: echo ${{ steps.broken-link.outputs.output }}
```

The issue seems to be related to invalid YAML formatting in `action.yml` file.
